In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim

df = pd.read_csv("bonus.csv")
df.head()

,employee_id,performance,years_of_experience,projects_completed,bonus
0,EMP_001,7,1,3,116
1,EMP_002,4,8,10,136
2,EMP_003,8,4,5,150
3,EMP_004,5,4,7,118
4,EMP_005,7,5,6,146


In [2]:
X = df[["performance","years_of_experience","projects_completed"]].values
y = df[['bonus']].values
type(y)

numpy.ndarray

In [3]:
type(df[['bonus']])

pandas.core.frame.DataFrame

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [5]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,dtype=torch.float32)

In [6]:
class BonusPrediction(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3,1)    
        )
    def forward(self,x):
        return self.network(x)

In [7]:
model = BonusPrediction()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.005)

In [8]:
epochs = 5000

for epoch in range(epochs):
    prediction = model(X_train_tensor)
    loss = criterion(prediction,y_train_tensor)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1)%100 == 0:
        print(f"Epoch: [{epoch+1}/{epochs}, Loss: {loss.item():.4f}")

Epoch: [100/5000, Loss: 22.1817
Epoch: [200/5000, Loss: 19.0681
Epoch: [300/5000, Loss: 16.6121
Epoch: [400/5000, Loss: 14.5514
Epoch: [500/5000, Loss: 12.7743
Epoch: [600/5000, Loss: 11.2241
Epoch: [700/5000, Loss: 9.8655
Epoch: [800/5000, Loss: 8.6725
Epoch: [900/5000, Loss: 7.6243
Epoch: [1000/5000, Loss: 6.7028
Epoch: [1100/5000, Loss: 5.8928
Epoch: [1200/5000, Loss: 5.1807
Epoch: [1300/5000, Loss: 4.5547
Epoch: [1400/5000, Loss: 4.0043
Epoch: [1500/5000, Loss: 3.5204
Epoch: [1600/5000, Loss: 3.0950
Epoch: [1700/5000, Loss: 2.7210
Epoch: [1800/5000, Loss: 2.3922
Epoch: [1900/5000, Loss: 2.1031
Epoch: [2000/5000, Loss: 1.8490
Epoch: [2100/5000, Loss: 1.6255
Epoch: [2200/5000, Loss: 1.4291
Epoch: [2300/5000, Loss: 1.2564
Epoch: [2400/5000, Loss: 1.1046
Epoch: [2500/5000, Loss: 0.9711
Epoch: [2600/5000, Loss: 0.8538
Epoch: [2700/5000, Loss: 0.7506
Epoch: [2800/5000, Loss: 0.6599
Epoch: [2900/5000, Loss: 0.5802
Epoch: [3000/5000, Loss: 0.5100
Epoch: [3100/5000, Loss: 0.4484
Epoch: [320

In [11]:
model.eval()

predictions = model(X_test_tensor)
loss = criterion(predictions,y_test_tensor)
loss

tensor(0.0373, grad_fn=<MseLossBackward0>)

In [12]:
predictions[:5]

tensor([[161.8629],
        [133.7964],
        [131.9738],
        [113.7582],
        [ 79.7781]], grad_fn=<SliceBackward0>)

In [13]:
y_test_tensor[:5]

tensor([[162.],
        [134.],
        [132.],
        [114.],
        [ 80.]])

In [17]:
for name,values in model.named_parameters():
    print(name,values)

network.0.weight Parameter containing:
tensor([[12.0317,  5.8477,  2.1807]], requires_grad=True)
network.0.bias Parameter containing:
tensor([19.2616], requires_grad=True)


In [19]:
x = model.named_parameters()
x.

<generator object Module.named_parameters at 0x1511a8640>